"""Project-related schemas."""

from enum import Enum
from typing import List, Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field


class ProjectType(str, Enum):
    """Types of projects the system can generate."""

    RESEARCH = "research"  # Market research, user research, competitive analysis
    PRODUCT = "product"  # Product spec, feature design, prototype
    CAMPAIGN = "campaign"  # Marketing campaign, content strategy
    STARTUP = "startup"  # Business plan, MVP, go-to-market


class DeliverableType(BaseModel):
    """Definition of a project deliverable."""

    name: str
    description: str
    format: str  # e.g., "PDF report", "Figma prototype", "Slide deck"
    evaluation_criteria: List[str]


class ProjectProposal(BaseModel):
    """Project proposal generated by Project Generator agent."""

    title: str
    project_type: ProjectType

    description: str = Field(
        ...,
        description="Detailed project description and context"
    )

    why_relevant: str = Field(
        ...,
        description="Why this project is relevant for the target role/domain"
    )

    deliverables: List[DeliverableType]

    estimated_duration_weeks: float = Field(
        ge=2.0,
        le=3.0,
        description="Estimated completion time in weeks"
    )

    skills_demonstrated: List[str] = Field(
        ...,
        description="Skills this project will demonstrate"
    )

    recruiter_appeal: str = Field(
        ...,
        description="Why recruiters will value this project"
    )

    evaluation_criteria: List[str] = Field(
        ...,
        description="Criteria for evaluating project success"
    )


class Project(BaseModel):
    """Complete project model."""

    project_id: str
    user_id: str

    proposal: ProjectProposal

    status: str = "proposed"  # proposed, active, completed

    created_at: datetime = Field(default_factory=datetime.utcnow)
    approved_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    # Links to problem and solution
    problem_id: Optional[str] = None
    solution_id: Optional[str] = None

    # Metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        use_enum_values = True
